# times are UTC
# dates are DD/MM/YYYY
# times are HH:MM (24-hour clock)
# Platforms: PC, Playstation, Xbox, Nintendo
# updates can be made to a row by specifying an ID
# deletions can be made by specifying an ID and setting the "Delete" field to "true"

#[[streams]]
#  ID = 0
#  Delete = ""
#  Name = ""
#  Platform = ""
#  Date = ""
#  Time = ""
#  Description = ""
#  URL = ""

[[streams]]
  Name = "The Indie Horror Showcase"
  Platform = "PC, Playstation, Xbox, Nintendo"
  Date = "24/10/2024"
  Time = ""
  Description = "Launched in 2023 by the independent horror games publisher DreadXP, The Indie Horror Showcase is both an event and celebration of the the indie horror development community and the wide variety of creativity it represesnts."
  URL = "https://www.youtube.com/@IGN/live"

[[streams]]
  Name = "The Game Awards"
  Platform = "PC, Playstation, Xbox, Nintendo"
  Date = "12/12/2024"
  Time = ""
  Description = "The Game Awards 10th Anniversary broadcast from Peacock Theater in Los Angeles."
  URL = "https://www.twitch.tv/thegameawards"

[[streams]]
  Name = "The Horror Game Awards"
  Platform = "PC, Playstation, Xbox, Nintendo"
  Date = "14/12/2024"
  Time = ""
  Description = "The Horror Game Awards will be streaming LIVE for the THIRD TIME. Honouring the year's best games from the world of horror and showcasing all the video game scares we have to look forward to in the future."
  URL = "https://www.youtube.com/@HorrorGameAwards/live"

[[streams]]
  Name = "INDIE Live Expo"
  Platform = "PC, Playstation, Xbox, Nintendo"
  Date = "07/12/2024"
  Time = ""
  Description = "INDIE Live Expo, Japan’s premiere online digital showcase series connecting indie game fans all over the world, announces the return of INDIE Live Expo 2024.12.7."
  URL = "https://www.youtube.com/@indieliveexpo/live"

[[streams]]
  Name = "INDIE Live Expo Awards"
  Platform = "PC, Playstation, Xbox, Nintendo"
  Date = "07/12/2024"
  Time = ""
  Description = "The annual INDIE Live Expo Awards will feature a panel of global games industry veterans bestowing accolades to critically acclaimed recent titles."
  URL = "https://www.youtube.com/@indieliveexpo/live"

[[streams]]
  Name = "NVIDIA @ CES 2025"
  Platform = "PC"
  Date = "07/01/2025"
  Time = "01:30"
  Description = "Tune in to the CES opening keynote by NVIDIA CEO Jensen Huang live in Las Vegas."
  URL = "https://www.youtube.com/@NVIDIA/live"

[[streams]]
  Name = "PC Gaming Show"
  Platform = "PC"
  Date = "05/12/2024"
  Time = ""
  Description = "The PC Gaming Show is back, and it’s bringing a hefty sack of videogame magic when it hits this December 5. What have we got in our bag? Oh, you know, just a buffet of premieres, announcements, and interviews that bring out the best of the best of the best of PC gaming."
  URL = "https://www.twitch.tv/pcgamer"

  #[[streams]]
  #  Name = "AMD @ CES 2025"
  #  Platform = "PC"
  #  Date = ""
  #  Time = "
  #  Description = ""
  #  URL = "https://www.youtube.com/@AMD/live"

  #[[streams]]
  #  Name = "Day of the Devs: Game Awards Edition"
  #  Platform = "PC, Playstation, Xbox, Nintendo"
  #  Date = ""
  #  Time = ""
  #  Description = "We will be hosting a Day of the Devs digital-only event following the Game Awards in December, 2024."
  #  URL = ""

  #[[streams]]
  #  Name = "Latin American Games Showcase: Game Awards Edition"
  #  Platform = "PC, Playstation, Xbox, Nintendo"
  #  Date = "12/12/2024"
  #  Time = "12:00"
  #  Description = "LAGS strives to be a platform with great visibility for the games developed in Latin America or by Latin American teams around the world. Our next showcase will take place on December in collaboration with The Game Awards."
  #  URL = ""

  #[[streams]]
  #  Name = "Access-Ability Winter Showcase"
  #  Platform = "PC, Playstation, Xbox, Nintendo"
  #  Date = "12/12/2024"
  #  Time = ""
  #  Description = "The Access-Ability Summer Showcase is aiming to become twice annual with the introduction of a Winter Showcase. "
  #  URL = ""
