# times are UTC
# dates are DD/MM/YYYY
# times are HH:MM (24-hour clock)
# Platforms: PC, Playstation, Xbox, Nintendo
# updates can be made to a row by specifying an ID
# deletions can be made by specifying an ID and setting the "Delete" field to "true"

#[[streams]]
#  ID = 0
#  Delete = ""
#  Name = ""
#  Platform = ""
#  Date = ""
#  Time = ""
#  Description = ""
#  URL = ""

[[streams]]
  Name = "Upload VR Showcase"
  Platform = "PC, Playstation"
  Date = "26/06/2024"
  Time = "17:00"
  Description = "We've got dozens of videos in hand for the UploadVR Summer Showcase featuring impressive new work from developers exploring funny, strange and wildly cool new ideas for headsets."
  URL = "https://www.youtube.com/@Uploadvr/live"
