# times are UTC
# Nintendo Direct, Sony State of Play, Xbox Inside
# The Streamer Awards, The Game Awards, Summer Game Fest, Future Games Show, Gamescom

[[streams]]
  Name = "TEST STREAM 1"
  Platform = "TEST PLATFORM 1"
  Date = "2024-03-02"
  Time = "19:00"
  Description = "TEST DESCRIPTION 1"
  URL = "https://www.twitch.tv/TEST1"

[[streams]]
  Name = "TEST STREAM 2"
  Platform = "TEST PLATFORM 2"
  Date = "2024-07-15"
  Time = "21:00"
  Description = "TEST DESCRIPTION 2"
  URL = "https://www.twitch.tv/TEST2"

[[streams]]
  Name = "TEST STREAM 3"
  Platform = "TEST PLATFORM 3"
  Date = "2024-01-15"
  Time = "21:00"
  Description = "TEST DESCRIPTION 3"
  URL = "https://www.twitch.tv/TEST3"
