# times are UTC
# dates are DD/MM/YYYY
# times are HH:MM (24-hour clock)
# Platforms: PC, Playstation, Xbox, Nintendo
# updates can be made to a row by specifying an ID
# deletions can be made by specifying an ID and setting the "Delete" field to "true"

#[[streams]]
#  ID = 0
#  Delete = ""
#  Name = ""
#  Platform = ""
#  Date = ""
#  Time = ""
#  Description = ""
#  URL = ""

[[streams]]
  Name = "Future Games Show Summer Edition"
  Platform = "PC, Playstation, Xbox, Nintendo"
  Date = "07/06/2025"
  Time = ""
  Description = "Mark your calendars, friends – the Future Games Show Summer Showcase returns on Saturday, June 7! Featuring: World premieres, Exclusive trailers + Game demos."
  URL = "https://www.youtube.com/@FutureGamesShow/live"

[[streams]]
  Name = "Day of the Devs: Summer Game Fest Edition"
  Platform = "PC, Playstation, Xbox, Nintendo"
  Date = "06/06/2025"
  Time = "23:00"
  Description = "A look at upcoming indie games from the non-profit Day of the Devs."
  URL = "https://www.twitch.tv/thegameawards"

[[streams]]
  Name = "The Elder Scrolls IV: Oblivion Remaster Showcase"
  Platform = "PC, Playstation, Xbox"
  Date = "22/04/2025"
  Time = "15:00"
  Description = "Announcement showcase for the remaster of The Elder Scrolls IV: Oblivion."
  URL = "https://www.twitch.tv/bethesda"
