# times are UTC
# dates are DD/MM/YYYY
# times are HH:MM (24-hour clock)
# Platforms: PC, Playstation, Xbox, Nintendo
# updates can be made to a row by specifying an ID
# deletions can be made by specifying an ID and setting the "Delete" field to "true"

#[[streams]]
#  ID = 0
#  Delete = ""
#  Name = ""
#  Platform = ""
#  Date = ""
#  Time = ""
#  Description = ""
#  URL = ""

[[streams]]
  Name = "The Indie Horror Showcase"
  Platform = "PC, Playstation, Xbox, Nintendo"
  Date = "24/10/2024"
  Time = ""
  Description = "Launched in 2023 by the independent horror games publisher DreadXP, The Indie Horror Showcase is both an event and celebration of the the indie horror development community and the wide variety of creativity it represesnts."
  URL = "https://www.youtube.com/@IGN/live"

[[streams]]
  Name = "RGG Summit 2024"
  Platform = "PC, Playstation, Xbox, Nintendo"
  Date = "20/09/2024"
  Time = "10:00"
  Description = "The RGG Summit is a yearly event that brings together the developers, publishers, and fans of the Yakuza and Judgment series."
  URL = "https://www.youtube.com/live/uHui_T50w8M"

[[streams]]
  Name = "The Game Awards"
  Platform = "PC, Playstation, Xbox, Nintendo"
  Date = "12/12/2024"
  Time = ""
  Description = "The Game Awards 10th Anniversary broadcast from Peacock Theater in Los Angeles."
  URL = "https://www.twitch.tv/thegameawards"

[[streams]]
  Name = "The Horror Game Awards"
  Platform = "PC, Playstation, Xbox, Nintendo"
  Date = "14/12/2024"
  Time = ""
  Description = "The Horror Game Awards will be streaming LIVE for the THIRD TIME. Honouring the year's best games from the world of horror and showcasing all the video game scares we have to look forward to in the future."
  URL = "https://www.youtube.com/@HorrorGameAwards/live"
