# times are UTC
# dates are DD/MM/YYYY
# times are HH:MM (24-hour clock)
# updates can be made to a row by specifying an ID
# deletions can be made by specifying an ID and setting the "Delete" field to "true"

#[[streams]]
#  ID = 0
#  Delete = ""
#  Name = ""
#  Platform = ""
#  Date = ""
#  Time = ""
#  Description = ""
#  URL = ""
