# times are UTC
# dates are DD/MM/YYYY
# times are HH:MM (24-hour clock)
# Platforms: PC, Playstation, Xbox, Nintendo
# updates can be made to a row by specifying an ID
# deletions can be made by specifying an ID and setting the "Delete" field to "true"

#[[streams]]
#  ID = 0
#  Delete = ""
#  Name = ""
#  Platform = ""
#  Date = ""
#  Time = ""
#  Description = ""
#  URL = ""

[[streams]]
  Name = "Capcom Next"
  Platform = "PC, Playstation, Xbox"
  Date = "01/07/2024"
  Time = "22:00"
  Description = "Your favorite Zombie Paradise is back from the dead! We have the surprise announcement of Dead Rising Deluxe Remaster. We'll also be providing updates about Kunitsu-Gami: Path of the Goddess, which launches on July 19, and RESIDENT EVIL 7 biohazard for iPhone/iPad/Mac at this digital event."
  URL = "https://www.twitch.tv/capcomusa"
